### ISSUE TITLE
writeCSV

### ISSUE THREAD

**Issue by nichhenr** [collinn/bdots#24]
I'm using the bdots package to analyze time-series data by group. Everything works great until I try to write the bootstrapped data to a CSV. If there are differences between the two groups I choose, then writeCSV works as expected. If not, then it fails with the error:

Error in seq_len(nrow(st)) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(nrow(st)) : first element used of 'length.out' argument

The code is below. In this example, selecting groups 1 and 2 in the Bootstrap produces the error. Changing this to group 1 and 3 will produce results. The data are attached here:
[TTC BDOTS.xlsx](https://github.com/collinn/bdots/files/9013709/TTC.BDOTS.xlsx)

```
library(bdots)
library(tidyr)
library(ggplot2)
library(readxl)
library(tidyverse)
vignette("bdots") #view the Bdots vignette for more explanation

#Load File & Setup Data Frame
GCAWide<- read_excel(file.choose())
BDOTS<-pivot_longer(GCAWide, cols=num_range("",1:50), names_to="Time", values_to="Accuracy")
BDOTS$Time<-as.numeric(BDOTS$Time)

####### Fitting Step ######################################################################

BDfit <- bdotsFit(data = BDOTS,
                  subject = "Subject",
                  time = "Time",
                  y = "Accuracy",
                  group = "Group",
                  curveType = polynomial(degree=3),
                  cores = 2)
view(BDfit)
table(BDfit$fitCode)

head(coef(BDfit))
plot(BDfit[1:4,])

####### Refitting Step ######################################################################

#Run Refit
table(BDfit$fitCode)
BDrefit <- bdotsRefit(BDfit, fitCode = 1L, quickRefit = TRUE)
table(BDrefit$fitCode)

## Manual refit (not run)
#refit <- bdotsRefit(fit, fitCode = 1L)

## Remove all failed curve fits from refit
BDrefit <- bdRemove(BDrefit, fitCode = 6L)
table(BDrefit$fitCode)

####### Bootstrapping ######################################################################

BDBoot1 <- bdotsBoot(formula = Accuracy ~ Group(1, 2),
                   bdObj = BDrefit,
                   Niter = 1000,
                   alpha = 0.05,
                   padj = "oleson",
                   cores = 2)
summary(BDBoot1)
plot(BDBoot1, ciBands=TRUE, plotDiffs=FALSE)
writeCSV(BDBoot1, "Bootstraps.csv", alpha=0.05)
```

**Comment by collinn** [comment]
Great catch, thanks for reporting with code and data. I identified the issue and just pushed the fix up to github now. Let me know if you run into any other problems

**Comment by nichhenr** [comment]
Thanks for your help. I'm glad to see the fix seemed quick and easy. I'm a bit of a newbie, so I'm not sure how I actually use this now that it's on GitHub. I think I'm looking at the write raw file (https://raw.githubusercontent.com/collinn/bdots/master/R/writeCSV.R) but I'm not quite sure what to do with it from here. Can you provide a bit of guidance? Thanks again!

**Comment by collinn** [comment]
Hey no problem at all, I'm happy to help any way I can.

To install the most up to date version from github, you can use this code
`install.packages("devtools")`
`devtools::install_github("collinn/bdots")`

Give that a shot and let me know if you are able to get it working

**Comment by nichhenr** [comment]
After a bit of trouble installing devtools (my problem, not yours!), it works brilliantly. Thank you so much for your help. I think the BDOTs approach will really add a lot to the project that I'm working on, and it's really useful to be able to extract the bootstrapped values and plug them into ggplot (even though the plot() function is amazingly simple and effective in it's own right!).

Thanks again!
