### ISSUE TITLE
Error Plotting after update

### ISSUE THREAD

**Issue by nichhenr** [collinn/bdots#29]
I'm using the bdots package to analyze time-series data by group. These are data that I've been working with for the past 6 months. After the recent(?) update to 1.2.5, everything works except for when I try plotting individual participant curves. When doing this, I get an error:

> plot(BDfit[1:4,])
Error in data.table::rbindlist(list(dfobs, dffit)) : 
  Class attribute on column 2 of item 2 does not match with column 2 of item 1
 
This is the same code and data from my last post (which didn't throw the error). The code is below, and the data are attached here:
[TTC BDOTS.xlsx](https://github.com/collinn/bdots/files/9013709/TTC.BDOTS.xlsx)

######################################################################
library(bdots)
library(tidyr)
library(ggplot2)
library(readxl)
library(tidyverse)
vignette("bdots") #view the Bdots vignette for more explanation

#Load File & Setup Data Frame
GCAWide<- read_excel(file.choose())
BDOTS<-pivot_longer(GCAWide, cols=num_range("",1:50), names_to="Time", values_to="Accuracy")
BDOTS$Time<-as.numeric(BDOTS$Time)

####### Fitting Step ######################################################################

BDfit <- bdotsFit(data = BDOTS,
                  subject = "Subject",
                  time = "Time",
                  y = "Accuracy",
                  group = "Group",
                  curveType = polynomial(degree=3),
                  cores = 2)
view(BDfit)
table(BDfit$fitCode)

head(coef(BDfit))
plot(BDfit[1:4,])
######################################################################

**Comment by collinn** [comment]
Hey, sorry about this -- there are a few issues with that version, which is actually rolled back from an older version, prior to any bugs being fixed. There are some drastic methodology changes coming in the next patch which should be put out before long.

For now,  your best bet is to roll back to the version just prior to that update. You can do that with

```
package = "https://cran.r-project.org/package=bdots&version=1.2.0"
utils::install.packages(pkgs = package, repos = NULL)
```

My apologies again for the issues -- please don't hesitate to let me know if you run into any more problems

**Comment by nichhenr** [comment]
Thanks Colin. I'm unfortunately still getting the error. Maybe it has to do with the version of data.table I'm running (1.14.6)? Here's my session info:

`R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gridExtra_2.3     forcats_0.5.1     stringr_1.5.0     dplyr_1.1.0       purrr_1.0.1      
 [6] readr_2.1.2       tibble_3.1.7      tidyverse_1.3.1   readxl_1.4.0      ggplot2_3.4.0    
[11] tidyr_1.3.0       bdots_1.2.0       data.table_1.14.6

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.0 haven_2.5.0      lattice_0.20-45  colorspace_2.0-3 vctrs_0.5.2     
 [6] generics_0.1.2   utf8_1.2.2       rlang_1.0.6      pillar_1.8.1     glue_1.6.2      
[11] withr_2.5.0      DBI_1.1.3        bit64_4.0.5      dbplyr_2.2.1     modelr_0.1.8    
[16] lifecycle_1.0.3  munsell_0.5.0    gtable_0.3.1     cellranger_1.1.0 rvest_1.0.2     
[21] mvtnorm_1.1-3    labeling_0.4.2   tzdb_0.3.0       librarian_1.8.1  parallel_4.2.1  
[26] fansi_1.0.3      broom_0.8.0      backports_1.4.1  scales_1.2.1     vroom_1.5.7     
[31] jsonlite_1.8.0   bit_4.0.4        farver_2.1.1     fs_1.5.2         hms_1.1.1       
[36] stringi_1.7.6    cli_3.6.0        tools_4.2.1      magrittr_2.0.3   crayon_1.5.1    
[41] pkgconfig_2.0.3  ellipsis_0.3.2   xml2_1.3.3       reprex_2.0.1     lubridate_1.8.0 
[46] assertthat_0.2.1 httr_1.4.3       rstudioapi_0.13  R6_2.5.1         nlme_3.1-157    
[51] compiler_4.2.1 `

**Comment by collinn** [comment]
Got it. Sneaky. Thank you so much for including your code and example data.

The issue has to do with the `polynomial` function being used in ways I'm not quite sure I understand just yet. At any rate, we can resolve this by using the `polynomial2` function I've pasted below. Just run that function so that it's in your environment and you'll be able to use it in the exact same way as `polynomial`. I went ahead and tried fitting and bootstrapping to make sure that I didn't run into any other immediate issues and it seems like things are going fine. You'll want to keep using this `polynomial2` function until I'm able to get the next update out. Thanks again for your patience, and of course feel free to let me know if you have any other issues

```
polynomial2 <- function(dat, y, time, degree, raw = TRUE, params = NULL, ...)  {
  polyPars <- function(dat, y, time, degree, raw) {
    if (var(dat[[y]]) == 0) {
      return(NULL)
    }
    pp <- lm(dat[[y]] ~ poly(dat[[time]], degree = degree, raw = raw))
    setNames(coef(pp), c(paste0("beta", seq(degree + 1L))))
  }
  if (is.null(params)) {
    params <- polyPars(dat, y, time, degree, raw)
  } else {
    if (length(params) != degree + 1L) stop("poly requires that number of params matches degree + 1 (for intercept)")
    if (!all(names(params) %in% paste0("beta", seq(degree + 1L)))) {
      stop("polynomial parameters must be labeled beta1, ..., beta[degree + 1]")
    }
  }
  ## Return NA list if var(y) is 0
  if (is.null(params)) {
    return(NULL)
  }
  time_names <- paste0("(Time^", seq(degree + 1L) - 1L , ")")
  ff <- paste(names(params), time_names, sep = "*", collapse = "+")
  ff <- str2lang(ff)
  y <- str2lang(y)
  ff <- bquote(.(y) ~ .(ff))
  attr(ff, "parnames") <- names(params)
  return(list(formula = ff, params = params))
}
```

**Comment by nichhenr** [comment]
As always, thanks for your super quick and helpful response. This has solved the issue, so I'll use this solution until a new version is released. Thanks!
